import sqlite3

# Define all 30 questions
questions_data = [
    {
        'id': 1,
        'question': 'Which implant helps regulate irregular heart rhythms?',
        'option_a': 'Pacemaker',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Cochlear Implant',
        'option_d': 'Knee Brace',
        'correct_answer': 'A',
        'body_part': 'Heart',
    },
    {
        'id': 2,
        'question': 'What implant is commonly used to restore hearing in patients with severe hearing loss?',
        'option_a': 'Retinal Implant',
        'option_b': 'Cochlear Implant',
        'option_c': 'Dental Implant',
        'option_d': 'Hip Prosthesis',
        'correct_answer': 'B',
        'body_part': 'Ear',
    },
    {
        'id': 3,
        'question': 'Which implant replaces a damaged hip joint?',
        'option_a': 'Knee Prosthesis',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Shoulder Sling',
        'option_d': 'Elbow Plate',
        'correct_answer': 'B',
        'body_part': 'Hip',
    },
    {
        'id': 4,
        'question': 'What implant is used to replace a damaged shoulder joint?',
        'option_a': 'Shoulder Prosthesis',
        'option_b': 'Ankle Brace',
        'option_c': 'Hip Spacer',
        'option_d': 'Foot Orthosis',
        'correct_answer': 'A',
        'body_part': 'Shoulder',
    },
    {
        'id': 5,
        'question': 'Which implant is designed to replace or support an injured elbow joint?',
        'option_a': 'Knee Brace',
        'option_b': 'Elbow Prosthesis',
        'option_c': 'Wrist Splint',
        'option_d': 'Hip Spacer',
        'correct_answer': 'B',
        'body_part': 'Elbow',
    },
    {
        'id': 6,
        'question': 'What implant replaces a damaged knee joint to restore mobility?',
        'option_a': 'Knee Prosthesis',
        'option_b': 'Shoulder Plate',
        'option_c': 'Hip Screw',
        'option_d': 'Elbow Brace',
        'correct_answer': 'A',
        'body_part': 'Knee',
    },
    {
        'id': 7,
        'question': 'Which implant assists with ankle movement after severe injury?',
        'option_a': 'Hip Prosthesis',
        'option_b': 'Ankle Prosthesis',
        'option_c': 'Shoulder Sling',
        'option_d': 'Knee Brace',
        'correct_answer': 'B',
        'body_part': 'Foot',
    },
    {
        'id': 8,
        'question': 'What is the implant called that replaces a missing arm?',
        'option_a': 'Arm Prosthesis',
        'option_b': 'Leg Brace',
        'option_c': 'Cochlear Implant',
        'option_d': 'Hip Spacer',
        'correct_answer': 'A',
        'body_part': 'Arm',
    },
    {
        'id': 9,
        'question': 'Which implant is used to replace damaged heart valves?',
        'option_a': 'Cardiac Stent',
        'option_b': 'Artificial Heart Valve',
        'option_c': 'Pacemaker',
        'option_d': 'Defibrillator',
        'correct_answer': 'B',
        'body_part': 'Heart',
    },
    {
        'id': 10,
        'question': 'What device is implanted to keep arteries open in the heart?',
        'option_a': 'Cochlear Implant',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Coronary Stent',
        'option_d': 'Knee Brace',
        'correct_answer': 'C',
        'body_part': 'Heart',
    },
    {
        'id': 11,
        'question': 'Which implant helps patients with foot drop to walk more naturally?',
        'option_a': 'Foot Orthosis',
        'option_b': 'Hip Spacer',
        'option_c': 'Knee Prosthesis',
        'option_d': 'Elbow Plate',
        'correct_answer': 'A',
        'body_part': 'Foot',
    },
    {
        'id': 12,
        'question': 'What implant is used to reconstruct the eardrum?',
        'option_a': 'Tympanic Membrane Graft',
        'option_b': 'Cochlear Implant',
        'option_c': 'Dental Implant',
        'option_d': 'Hip Prosthesis',
        'correct_answer': 'A',
        'body_part': 'Ear',
    },
    {
        'id': 13,
        'question': 'Which implant aids in stabilizing a fractured shoulder blade?',
        'option_a': 'Shoulder Plate',
        'option_b': 'Knee Brace',
        'option_c': 'Hip Spacer',
        'option_d': 'Ankle Prosthesis',
        'correct_answer': 'A',
        'body_part': 'Shoulder',
    },
    {
        'id': 14,
        'question': 'What implant is used to repair a torn anterior cruciate ligament (ACL) in the knee?',
        'option_a': 'Hip Prosthesis',
        'option_b': 'Knee Ligament Graft',
        'option_c': 'Elbow Plate',
        'option_d': 'Cochlear Implant',
        'correct_answer': 'B',
        'body_part': 'Knee',
    },
    {
        'id': 15,
        'question': 'Which implant is designed to replace a missing hand?',
        'option_a': 'Hip Prosthesis',
        'option_b': 'Hand Prosthesis',
        'option_c': 'Foot Orthosis',
        'option_d': 'Knee Brace',
        'correct_answer': 'B',
        'body_part': 'Arm',
    },
    {
        'id': 16,
        'question': 'What implant assists with blood flow between the heart and lungs in infants with congenital defects?',
        'option_a': 'Pacemaker',
        'option_b': 'Blalock-Taussig Shunt',
        'option_c': 'Coronary Stent',
        'option_d': 'Artificial Heart Valve',
        'correct_answer': 'B',
        'body_part': 'Heart',
    },
    {
        'id': 17,
        'question': 'Which implant replaces the ball of the upper arm bone in shoulder replacements?',
        'option_a': 'Humeral Head Prosthesis',
        'option_b': 'Hip Spacer',
        'option_c': 'Knee Cap Prosthesis',
        'option_d': 'Elbow Plate',
        'correct_answer': 'A',
        'body_part': 'Shoulder',
    },
    {
        'id': 18,
        'question': 'What implant is used to fuse ankle bones in severe arthritis cases?',
        'option_a': 'Ankle Arthrodesis Plate',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Knee Brace',
        'option_d': 'Shoulder Sling',
        'correct_answer': 'A',
        'body_part': 'Foot',
    },
    {
        'id': 19,
        'question': 'Which implant is used to repair a torn rotator cuff in the shoulder?',
        'option_a': 'Rotator Cuff Patch',
        'option_b': 'Hip Spacer',
        'option_c': 'Knee Ligament Graft',
        'option_d': 'Elbow Plate',
        'correct_answer': 'A',
        'body_part': 'Shoulder',
    },
    {
        'id': 20,
        'question': 'What implant helps manage severe arthritis in the elbow?',
        'option_a': 'Elbow Prosthesis',
        'option_b': 'Knee Brace',
        'option_c': 'Ankle Prosthesis',
        'option_d': 'Cochlear Implant',
        'correct_answer': 'A',
        'body_part': 'Elbow',
    },
    {
        'id': 21,
        'question': 'Which implant is used in total knee replacement to mimic the function of cartilage?',
        'option_a': 'Polyethylene Insert',
        'option_b': 'Hip Spacer',
        'option_c': 'Shoulder Plate',
        'option_d': 'Elbow Brace',
        'correct_answer': 'A',
        'body_part': 'Knee',
    },
    {
        'id': 22,
        'question': 'What implant aids in correcting deformities in the foot\'s arch?',
        'option_a': 'Foot Orthotic Implant',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Knee Brace',
        'option_d': 'Shoulder Sling',
        'correct_answer': 'A',
        'body_part': 'Foot',
    },
    {
        'id': 23,
        'question': 'Which implant replaces the hip socket in a hip replacement surgery?',
        'option_a': 'Acetabular Cup',
        'option_b': 'Femoral Stem',
        'option_c': 'Knee Cap',
        'option_d': 'Shoulder Plate',
        'correct_answer': 'A',
        'body_part': 'Hip',
    },
    {
        'id': 24,
        'question': 'What implant is used to stabilize fractures in the forearm bones?',
        'option_a': 'Intramedullary Rod',
        'option_b': 'Hip Spacer',
        'option_c': 'Knee Ligament Graft',
        'option_d': 'Cochlear Implant',
        'correct_answer': 'A',
        'body_part': 'Arm',
    },
    {
        'id': 25,
        'question': 'Which implant helps in delivering electrical impulses to control chronic pain in the arm?',
        'option_a': 'Spinal Cord Stimulator',
        'option_b': 'Pacemaker',
        'option_c': 'Cochlear Implant',
        'option_d': 'Knee Brace',
        'correct_answer': 'A',
        'body_part': 'Arm',
    },
    {
        'id': 26,
        'question': 'What implant is used to replace the entire knee joint surface?',
        'option_a': 'Total Knee Arthroplasty Implant',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Elbow Plate',
        'option_d': 'Shoulder Sling',
        'correct_answer': 'A',
        'body_part': 'Knee',
    },
    {
        'id': 27,
        'question': 'Which implant is used to repair or replace a damaged heart\'s mitral valve?',
        'option_a': 'Mitral Valve Prosthesis',
        'option_b': 'Coronary Stent',
        'option_c': 'Pacemaker',
        'option_d': 'Defibrillator',
        'correct_answer': 'A',
        'body_part': 'Heart',
    },
    {
        'id': 28,
        'question': 'What implant aids in stabilizing the clavicle (collarbone) after a fracture?',
        'option_a': 'Clavicle Plate',
        'option_b': 'Knee Brace',
        'option_c': 'Hip Spacer',
        'option_d': 'Ankle Prosthesis',
        'correct_answer': 'A',
        'body_part': 'Shoulder',
    },
    {
        'id': 29,
        'question': 'Which implant is used to replace a damaged joint in the big toe?',
        'option_a': 'Great Toe Implant',
        'option_b': 'Hip Prosthesis',
        'option_c': 'Knee Ligament Graft',
        'option_d': 'Elbow Plate',
        'correct_answer': 'A',
        'body_part': 'Foot',
    },
    {
        'id': 30,
        'question': 'What implant is used to repair aneurysms in the heart\'s aorta?',
        'option_a': 'Aortic Stent Graft',
        'option_b': 'Pacemaker',
        'option_c': 'Coronary Stent',
        'option_d': 'Artificial Heart Valve',
        'correct_answer': 'A',
        'body_part': 'Heart',
    },
]

def initialize_database():
    conn = sqlite3.connect('quiz.db')
    cursor = conn.cursor()

    # Create tables
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS questions (
            id INTEGER PRIMARY KEY,
            question TEXT NOT NULL,
            option_a TEXT NOT NULL,
            option_b TEXT NOT NULL,
            option_c TEXT NOT NULL,
            option_d TEXT NOT NULL,
            correct_answer TEXT NOT NULL,
            body_part TEXT NOT NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS responses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            question_id INTEGER NOT NULL,
            selected_option TEXT NOT NULL,
            is_correct INTEGER NOT NULL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # Insert questions
    for q in questions_data:
        cursor.execute('''
            INSERT OR REPLACE INTO questions (id, question, option_a, option_b, option_c, option_d, correct_answer, body_part)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''', (q['id'], q['question'], q['option_a'], q['option_b'], q['option_c'], q['option_d'], q['correct_answer'], q['body_part']))

    conn.commit()
    conn.close()
    print("Database initialized successfully.")

if __name__ == '__main__':
    initialize_database()
